### ISSUE TITLE
I have the problem when "deeprank-gnn-esm-predict 1B6C.pdb "

### ISSUE THREAD

**Issue by liusfore** [DeepRank/DeepRank-GNN-esm#4]
2023-08-28 14:39:42,737 predict:218 INFO - Generating graph, using 95 processors
/mnt/data/anaconda/envs/deeprank-gnn-esm-gpu/lib/python3.9/site-packages/pdb2sql/interface.py:147: UserWarning: No contact atoms detected in pdb2sql
  warnings.warn('No contact atoms detected in pdb2sql')
Issue encountered while computing graph  /tmp/tmpckjcd5ha/1B6C.pkl
list index out of range
Graphs added to the HDF5 file
Traceback (most recent call last):
  File "/mnt/data/anaconda/envs/deeprank-gnn-esm-gpu/bin/deeprank-gnn-esm-predict", line 8, in <module>
    sys.exit(main())
  File "/mnt/data/anaconda/envs/deeprank-gnn-esm-gpu/lib/python3.9/site-packages/deeprank_gnn/predict.py", line 336, in main
    graph = create_graph(pdb_path=pdb_file.parent, workspace_path=workspace_path)
  File "/mnt/data/anaconda/envs/deeprank-gnn-esm-gpu/lib/python3.9/site-packages/deeprank_gnn/predict.py", line 223, in create_graph
    GraphHDF5(
  File "/mnt/data/anaconda/envs/deeprank-gnn-esm-gpu/lib/python3.9/site-packages/deeprank_gnn/GraphGenMP.py", line 141, in __init__
    self._add_embedding(outfile=outfile, pdbs=pdbs, embedding_path=embedding_path)
  File "/mnt/data/anaconda/envs/deeprank-gnn-esm-gpu/lib/python3.9/site-packages/deeprank_gnn/GraphGenMP.py", line 247, in _add_embedding
    assert not torch.all(torch.eq(embedding_tersor, 0))
AssertionError

**Comment by ntxxt** [comment]
Hi there,

It seems to be a problem with pdb2sql, no contacting atoms were found in the structure and it caused the following error. I can not reproduce this error with 1B6C.pdb. May I ask how you got your pdb file and what the version of your pdb2sql package is?

**Comment by jnoske** [comment]
Hi, I get the same error when I just download 1b6c from pdb and my pdb2sql version is 0.5.3.

**Comment by ntxxt** [comment]
Hi, Thanks for pointing it out. 

I apologize for mixing up the chainIDs in the example. ChainA and chainE are not interacting, which caused the error. I think it should work now. 

I also updated the code to support custom input chain IDs. Let me know if there is any issue. @jnoske @liusfore
